import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import Footer from "@/components/footer";
import HeaderNew from "@/components/header-new";
import Provider from "@/utils/Provider";
import ClientLayout from "../ClientLayout";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <ClientLayout>
          <Provider>
            <HeaderNew />
            {children}
            <Footer />
          </Provider>
        </ClientLayout>
      </body>
    </html>
  );
}
