import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import Footer from "@/components/footer";
import HeaderNew from "@/components/header-new";
import Provider from "@/utils/Provider";
import { Toaster } from "@/components/ui/toaster";
import ClientLayout from "../ClientLayout";
import { Suspense } from "react";
import Loading from "./loading";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "MALLU MART",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.ico" type="image/x-icon" />
        <link
          rel="shortcut icon"
          href="/favicon.ico"
          type="image/x-icon"
        />{" "}
        <title>{metadata?.title as string}</title>
        <meta name="description" content={metadata?.description as string} />
      </head>
      <body className={`${inter.className}`}>
        <ClientLayout>
          <Provider>
            <HeaderNew />
            <Suspense fallback={<Loading/>}>{children}</Suspense>
            <Footer />
            <Toaster />
          </Provider>
        </ClientLayout>
      </body>
    </html>
  );
}
